name: build lean4-cli

on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: build lean4-cli
    runs-on: ubuntu-latest
    steps:
      - uses: leanprover/lean-action@main
        with:
          test: false
